### ISSUE TITLE
Webm files are not recognized as a resource when they are in the VPK

### ISSUE THREAD

**Issue by DoctorGester** [ModDota/BugTracker#39]
Webm files can't be placed in a content folder, they do not compile into anything. They can be placed into a game folder and load fine from there in tools mode. Publishing the game makes it so those videos do not load anymore.

**Comment by SinZ163** [comment]
Are you trying to override existing Webm's or adding your own?

If you are trying to override it won't work purely due to them being already loaded so your override is too late, in tools mode your addon game folder is loaded before anything else, so you get in first but when its shipped through workshop, its only mounted by request so the game files beat you to the punch.

**Comment by DoctorGester** [comment]
Existing webms. None of the Valve-provided webms are located in the VPK, that's why they work.

**Comment by DoctorGester** [comment]
This seems to work now:

https://github.com/dota2unofficial/overthrow2/commit/129e0d1b58e66acb18003471da6ef850cb295512
